site_name: 'python-app'
site_url: https://www.mkdocs.org/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: blob/master/docs/

nav:
  - Overview: 
    - Getting Started: docs/index.md


plugins:
  - techdocs-core
